version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: django-v6-template-local
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-api_core.settings.dev}
      COLLECTSTATIC: "0"
    volumes:
      - ./:/app
    command: /entrypoint.sh
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]


