version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-v6-template
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-api_core.settings.prod}
      # Use Redis externo: defina REDIS_URL no .env (ex.: redis://host:6379/0)
    command: /entrypoint.sh
    restart: unless-stopped
