# Generated by Django 6.0a1 on 2025-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailuser",
            name="log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailuser",
            name="send",
            field=models.BooleanField(default=False),
        ),
    ]
