# Generated by Django 6.0a1 on 2025-09-26 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_emailuser_log_emailuser_send"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailuser",
            old_name="send",
            new_name="sent",
        ),
    ]
