# Generated by Django 5.0.3 on 2025-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_updated",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("apps", models.JSONField(null=True)),
                ("obj_type", models.CharField(max_length=120, null=True)),
                ("obj_data", models.JSONField(null=True)),
                ("obj_cmd", models.CharField(max_length=20, null=True)),
                ("sent", models.DateTimeField(null=True)),
                ("received", models.DateTimeField(null=True)),
                ("processed", models.DateTimeField(null=True)),
                ("log", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Event Sync",
                "verbose_name_plural": "Events Sync",
            },
        ),
    ]
