# Generated by Django 6.0a1 on 2025-09-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_sync", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsync",
            old_name="dt_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="eventsync",
            old_name="dt_updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="eventsync",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
